apiVersion : apps/v1
kind: Deployment
metadata:
  name: saileemogalepipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saileemogalepipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: saileemogalepipelinesjavascriptdocker 
    spec:
      containers:
        - name: saileemogalepipelinesjavascriptdocker 
          image: aapocclustercontainerregistry.azurecr.io/saileemogalepipelinesjavascriptdocker
          ports:
          - containerPort: 8080